### PR TITLE
upload initial reference.bib & include zotero group link

### PR DESCRIPTION
**Pull request by PeerHerholz**

### CODE REVIEW

**Review by JoseAlanis — APPROVED** [review]
nice, just joined the zotero group :)

**Comment by JoseAlanis** [comment]
Also, there appears to be a problem with the Makefile for the Sphinx-Doc. That's probably ok for now, but I can have a look later.

**Comment by PeerHerholz** [comment]
Currently checking the problem.

**Comment by PeerHerholz** [comment]
It was related to the package name, hence I changed it from `mindboggle-mixedmodels` to `mindboggle_mixedmodels` which is smarter choice anyway.

**Pull request merged**
